---

- name: Include logstash installation
  ansible.builtin.import_tasks: 
    file: 01_install.yml

- name: Include logstash plugins
  ansible.builtin.import_tasks: 
    file: 02_plugins.yml

- name: Include logstash config
  ansible.builtin.import_tasks: 
    file: 03_config.yml

- name: Include logstash checks
  ansible.builtin.import_tasks: 
    file: 04_checks.yml
